#!/bin/bash
#TODO: create numbered options page..

#	1. authenticate with the github server to unlock features that require write permissions..
./bin/ghauth

#	2. read only option for downloading home configs and environment as initial setup..
#		a. link all of the home configuration files to this repo and make sure the permissions are correct.
install.sh
#		b. repo should already be cloned when the install.sh script is ran.
#		e. needs root access for sudo synchronization for specific files.
#		f. OR needs to adapt to a user environment without sudo.. (may not be possible for admins..)

#	3. authenticated options for pushing environment changes on local machine to forked ghrepo..
savenquit
#		a. this is separate from the homeconfigs command but should require the same testing of files before upload..
#		b. should eventually allow a numbered selection of individual files to sync with the repo. 
#		c. or a list of preferred files to update and sync using the staged commands. 
#		d. add tracking for branches, etc.. 

#	4. ro resync of local config files in case something became corrupt somewhere..
homepull
#TODO:	needs to be updated to only copy files that have newer modification dates.
#		a. simple system pull defined by checking files for modification times and replacing with older files..
#		b. possibly a check for newly installed software for dependency conflicts by using package manager cmds..

#	5. rw option to add a new file to the github repository defined by set criteria..
#TODO:	this is just to add options to create folders or whatever is in the remote section of the cheatsheet.
#		a. folder structure needs to be defined per architecture type
#		b. and shell environment style
#		c. other should allow addition of new arch and shell types..

#	6. set up login and logout environment overwrites in case of user takovers or error scenarios..

#		a. define fallback procedures in case of possible data corruption and permission overwrites by system..
