#!/bin/bash
# pull .aliases from skel..
sudo cp -v /etc/skel/.aliases /home/etch/.aliases 
sudo chown etch:etch /home/etch/.aliases 
sudo chmod 664 /home/etch/.aliases 
ls -A /home/etch/.aliases
# pull .bashrc from skel..
sudo cp -v /etc/skel/.bashrc.etch /home/etch/.bashrc 
sudo chown etch:etch /home/etch/.bashrc 
sudo chmod 664 /home/etch/.bashrc 
ls -A /home/etch/.bashrc 
# pull .profile from skel..
sudo cp -v /etc/skel/.profile /home/etch/.profile 
sudo chown etch:etch /home/etch/.profile 
sudo chmod 664 /home/etch/.profile 
ls -A /home/etch/.profile 
# pull .vimrc from skel..
sudo cp -v /etc/skel/.vimrc /home/etch/.vimrc 
sudo chown etch:etch /home/etch/.vimrc 
sudo chmod 664 /home/etch/.vimrc 
ls -A /home/etch/.vimrc 
# pull .zprofile from skel..
sudo cp -v /etc/skel/.zprofile /home/etch/.zprofile 
sudo chown etch:etch /home/etch/.zprofile 
sudo chmod 664 /home/etch/.zprofile 
ls -A /home/etch/.zprofile 
# pull .zshrc from skel..
sudo cp -v /etc/skel/.zshrc /home/etch/.zshrc 
sudo chown etch:etch /home/etch/.zshrc 
sudo chmod 664 /home/etch/.zshrc 
ls -A /home/etch/.zshrc 

