#!/bin/bash
failure=" Sorry, that is not an option.. you must type a number and hit enter."

input() {
	echo " Choose an option:"
	echo " 1. style.."
	echo " 2. preference.."
	echo " 3. efficiency.."
	read -r num
	if [ "$num" -eq 1 ]; then echo " 1. style!"; elif [ "$num" -eq 2 ]; then echo " 2. preference.."; elif  [ "$num" -eq 3 ]; then echo " 3. efficiency.."; else echo $failure; input; fi
}
input

